apiVersion: rrsd.zetaapps.in/v1alpha1
kind: EmeraldCreditAllocationPolicy
metadata:
  name: lsg.emerald.emeraldcreditallocationpolicy.9001

spec:
  metadata:
    id: emerald.emeraldcreditallocationpolicy.9001
    name: Smart Credit Allocation Policy
    description: Credit Allocation Policy for EMI Loans - Subprime Segment
    requester:
      module: futureme-loan-module
      moduleVersion: 1.0.0
    tenantId: '600309'
    tenantCode: lsg

  validFrom: '2024-01-01T00:00:00.000+05:30'
  validTill: '2999-12-31T00:00:00.000+05:30'

  name: Smart Loan Credit Allocation Policy
  description: Allocates incoming payments across penalties, fees, interest, and principal in priority order

  code: ECAPUS009001

  programs:
    - code: ELCPROGUS009001
      precedenceScore: 100

  templateCode: us-credit-subprime