kind: CreditAllocationPolicy
apiVersion: rrsd.zetaapps.in/v1alpha1
metadata:
  name: lsg.auraapps.creditallocationpolicy.module.creditallocationpolicytest
  labels:
    rrsd.zetaapps.in/day: day-zero
    module: auraapps
    rrsd.zetaapps.in/space: aws-default-pp-mumbai
  annotations:
    zeta.tech/resource-tags: '{"gitDbRepo":"tenant_configuration.aws-default-pp-mumbai.lsg","gitDbPath":"https://gitea.internal.mum1-pp.zetaapps.in/zetaengg/tenant_configuration.aws-default-pp-mumbai.lsg.git","filePath":"module_configurations/module_auraapps/credit-allocation-policy/credit-allocation-policy_creditallocationpolicytest.yaml","tenantCode":"lsg"}'
  namespace: auraapps
spec:
  metadata:
    id: auraapps.creditallocationpolicy.module.creditallocationpolicytest
    name: auraapps.creditallocationpolicy.module.creditallocationpolicytest
    description: auraapps.creditallocationpolicy.module.creditallocationpolicytest
    tenantId: '600309'
    tenantCode: lsg
  validFrom: '2000-01-01T00:00:00.000+07:00'
  validTill: '2999-01-22T00:00:00.000+07:00'
  name: Credit Allocation Policy
  description: Ruby Credit Allocation Policy
  code: CROUS001999
  programs:
  - code: CRAUS001001
    precedenceScore: '10'
  - code: CRAUS001002
    precedenceScore: '20'
  - code: CRAUS001003
    precedenceScore: '30'
  - code: CRAUS001004
    precedenceScore: '40'
  - code: CRAUS001005
    precedenceScore: '50'
  templateCode: us-credit
