apiVersion: rrsd.zetaapps.in/v1alpha1
kind: RubyCreditBureauReportingPolicy
metadata:
  name: lsg.ruby.rubycreditbureaureportingpolicy.3011
spec:
  metadata:
    id: ruby.rubycreditbureaureportingpolicy.3011
    name: 3011 Ruby Credit Bureau Reporting Policy
    description: 3011 Ruby Credit Bureau Reporting Policy
    requester:
      module: ruby-module-e2e
      moduleVersion: 0.0.1
    tenantId: '600309'
    tenantCode: lsg
  name: Ruby Credit Bureau Reporting Policy
  code: CBRUS003011
  description: Ruby Credit Bureau Reporting Policy
  provider: ruby
  reportToCreditBureau: true
  frequencyOfReporting: BILLING_CYCLE
  restrictedStatusesForBureauReporting:
    - tag://tradeline/LEVEL_0
    - tag://accountBlockStatus/LEVEL_1
    - tag://accountClosureStatus/LEVEL_3
    - tag://accountLifecycleStatus/LEVEL_5
    - tag://accountLifecycleStatus/LEVEL_6
  accountClosureReporting:
    status: CLOSURE_INITIATED
  immediateReportNewOpenedAccount: true
  addressPreference:
    - permanent
    - residence
  immediateReportingForTerminalStatus:
    - tagUri: tag://autoChargeOffStatus/LEVEL_2
      applicableField: finalChargeOffDate
      source: account
    - tagUri: tag://manualChargeOffStatus/LEVEL_2
      applicableField: finalChargeOffDate
      source: account
    - tagUri: tag://tradeline/LEVEL_0
      applicableField: deletionDate
      source: accountholder
    - tagUri: tag://manualBundleStatusDeceased/MBAD2
      applicableField: deceased_status_effective_date
      source: accountholder
    - tagUri: tag://manualBundleStatusBankruptcy/MBBK4
      applicableField: bankruptcy_effective_date
      source: accountholder
  associatedConsumerReporting:
    relationshipTypes:
      - ALL
      - SPOUSE
  validFrom: '2000-01-01T23:09:01.795+07:00'
  validTill: '2999-01-01T23:09:01.795+07:00'
  templateCode: us-credit
