kind: RubyCreditBureauReportingPolicy
apiVersion: rrsd.zetaapps.in/v1alpha1
metadata:
  name: lsg.ruby.rubycreditbureaureportingpolicy.module.6001
  labels:
    rrsd.zetaapps.in/day: day-zero
  annotations:
    zeta.tech/resource-tags: '{"gitDbRepo":"tenant_configuration.aws-default-pp-mumbai.lsg","gitDbPath":"https://gitea.internal.mum1-pp.zetaapps.in/zetaengg/tenant_configuration.aws-default-pp-mumbai.lsg.git","filePath":"module_configurations/module_ruby/credit-bureau-reporting-policies/ruby-credit-bureau-reporting-policy_6001.yaml","tenantCode":"lsg"}'
  namespace: ruby
spec:
  metadata:
    id: ruby.rubycreditbureaureportingpolicy.module.6001
    name: ruby.rubycreditbureaureportingpolicy.module.6001
    description: ruby.rubycreditbureaureportingpolicy.module.6001
    tenantId: '600309'
    tenantCode: lsg
  name: Ruby Credit Bureau Reporting Policy
  code: CBRUS006001
  description: Ruby Credit Bureau Reporting Policy
  provider: ruby
  reportToCreditBureau: true
  frequencyOfReporting: BILLING_CYCLE
  restrictedStatusesForBureauReporting:
    - tag://tradeline/LEVEL_0
    - tag://accountBlockStatus/LEVEL_1
    - tag://accountClosureStatus/LEVEL_2
    - tag://accountLifecycleStatus/LEVEL_5
    - tag://accountLifecycleStatus/LEVEL_6
  accountClosureReporting:
    status: CLOSURE_ACCEPTED
  immediateReportNewOpenedAccount: true
  addressPreference:
    - permanent
    - residence
    - default
  immediateReportingForTerminalStatus:
    - tagUri: tag://autoChargeOffStatus/LEVEL_0
      applicableField: finalChargeOffDate
      source: account
    - tagUri: tag://manualChargeOffStatus/LEVEL_0
      applicableField: effectiveFrom
      source: account
    - tagUri: tag://tradeline/LEVEL_0
      applicableField: deletionDate
      source: account
    - tagUri: tag://manualBundleStatusDeceased/MBAD1
      applicableField: deceased_status_effective_date
      source: account
    - tagUri: tag://manualBundleStatusBankruptcy/MBBK1
      applicableField: bankruptcy_effective_date
      source: account
  associatedConsumerReporting:
    relationshipTypes:
      - SPOUSE
  validFrom: '2000-01-01T23:09:01.795+07:00'
  validTill: '2999-01-01T23:09:01.795+07:00'
  templateCode: us-credit
