kind: RubyStatementPolicy
apiVersion: rrsd.zetaapps.in/v1alpha1
metadata:
  name: lsg.ruby.rubystatementpolicy.module.8005
  labels:
    rrsd.zetaapps.in/day: day-zero
  annotations:
    zeta.tech/resource-tags: '{"gitDbRepo":"tenant_configuration.aws-default-pp-mumbai.lsg","gitDbPath":"https://gitea.internal.mum1-pp.zetaapps.in/zetaengg/tenant_configuration.aws-default-pp-mumbai.lsg.git","filePath":"module_configurations/module_ruby/statement-policies/ruby-statement-policy_8005.yaml","tenantCode":"lsg"}'
  namespace: ruby
spec:
  metadata:
    id: ruby.rubystatementpolicy.module.8005
    name: ruby.rubystatementpolicy.module.8005
    description: ruby.rubystatementpolicy.module.8005
    tenantId: '600309'
    tenantCode: lsg
  validFrom: '2000-01-01T00:00:00.000+01:00'
  validTill: '2099-01-01T00:00:00.000+01:00'
  name: Statement Policy
  description: Statement Policy
  code: STMUS008005
  physicalStatementThreshold: '0'
  graceDays: 0
  payByHolidayTreatment: retainHoliday
  dueDaysCalculationMethod: DueDays
  dueDays: 5
  allowedStatementCycles:
    - billingCycle: CYCUS00800501
    - billingCycle: CYCUS00800502
    - billingCycle: CYCUS00800503
    - billingCycle: CYCUS00800504
    - billingCycle: CYCUS00800505
    - billingCycle: CYCUS00800506
    - billingCycle: CYCUS00800507
    - billingCycle: CYCUS00800508
    - billingCycle: CYCUS00800509
    - billingCycle: CYCUS00800510
    - billingCycle: CYCUS00800511
    - billingCycle: CYCUS00800512
    - billingCycle: CYCUS00800513
    - billingCycle: CYCUS00800514
    - billingCycle: CYCUS00800515
    - billingCycle: CYCUS00800516
    - billingCycle: CYCUS00800517
    - billingCycle: CYCUS00800518
    - billingCycle: CYCUS00800519
    - billingCycle: CYCUS00800520
    - billingCycle: CYCUS00800521
    - billingCycle: CYCUS00800522
    - billingCycle: CYCUS00800523
    - billingCycle: CYCUS00800524
    - billingCycle: CYCUS00800525
    - billingCycle: CYCUS00800526
    - billingCycle: CYCUS00800527
    - billingCycle: CYCUS00800528
  password: function password(context) { return 'password' }
  statementTemplateCode: https://hercules-assets.mum1-pp.zetaapps.in/statement-templates/3.15.0/vera/template.html
  applyLateFeesOn: GRACE_DATE
  valueDateOfLateFees: DUE_DATE
  ytdSummaryEnabled: true
  ytdSummaryStartDate: 1
  ytdSummaryStartMonth: 1
  isProbableLateFeeEnabled: true
  isSchumerBoxEnabled: true
  schumerMonthsToRepay: 36
  isInterestBreakupEnabled: true
  yearlyCycle: CYCUS00800529
  billingCycleChangeConfig:
    coolOffDaysBetweenBillingCycleChange: 0
    rules:
      - maxLimit: 10
        period: YEARLY
  templateCode: us-credit
