kind: RubyStatementPolicy
apiVersion: rrsd.zetaapps.in/v1alpha1
metadata:
  name: lsg.ruby.rubystatementpolicy.module.7001
  labels:
    rrsd.zetaapps.in/day: day-zero
  annotations:
    zeta.tech/resource-tags: '{"gitDbRepo":"tenant_configuration.aws-default-pp-mumbai.lsg","gitDbPath":"https://gitea.internal.mum1-pp.zetaapps.in/zetaengg/tenant_configuration.aws-default-pp-mumbai.lsg.git","filePath":"module_configurations/module_ruby/statement-policies/ruby-statement-policy_7001.yaml","tenantCode":"lsg"}'
  namespace: ruby
spec:
  metadata:
    id: ruby.rubystatementpolicy.module.7001
    name: ruby.rubystatementpolicy.module.7001
    description: ruby.rubystatementpolicy.module.7001
    tenantId: '600309'
    tenantCode: lsg
  validFrom: '2000-01-01T00:00:00.000+01:00'
  validTill: '2099-01-01T00:00:00.000+01:00'
  name: Statement Policy
  description: Statement Policy
  code: STMUK007001
  physicalStatementThreshold: '0'
  graceDays: 0
  payByHolidayTreatment: retainHoliday
  dueDaysCalculationMethod: DueDays
  dueDays: 1
  allowedStatementCycles:
    - billingCycle: CYCUK00700101
    - billingCycle: CYCUK00700102
    - billingCycle: CYCUK00700103
    - billingCycle: CYCUK00700104
    - billingCycle: CYCUK00700105
    - billingCycle: CYCUK00700106
    - billingCycle: CYCUK00700107
    - billingCycle: CYCUK00700108
    - billingCycle: CYCUK00700109
    - billingCycle: CYCUK00700110
    - billingCycle: CYCUK00700111
    - billingCycle: CYCUK00700112
    - billingCycle: CYCUK00700113
    - billingCycle: CYCUK00700114
    - billingCycle: CYCUK00700115
    - billingCycle: CYCUK00700116
    - billingCycle: CYCUK00700117
    - billingCycle: CYCUK00700118
    - billingCycle: CYCUK00700119
    - billingCycle: CYCUK00700120
    - billingCycle: CYCUK00700121
    - billingCycle: CYCUK00700122
    - billingCycle: CYCUK00700123
    - billingCycle: CYCUK00700124
    - billingCycle: CYCUK00700125
    - billingCycle: CYCUK00700126
    - billingCycle: CYCUK00700127
    - billingCycle: CYCUK00700128
    - billingCycle: CYCUK00700130
    - billingCycle: CYCUK00700131
    - billingCycle: CYCUK00700132
  password: function password(context) { return 'password' }
  statementTemplateCode: https://hercules-assets.mum1-pp.zetaapps.in/statement-templates/3.14.5/lumen/ziva/template.html
  applyLateFeesOn: GRACE_DATE
  valueDateOfLateFees: DUE_DATE
  ytdSummaryEnabled: true
  ytdSummaryStartDate: 1
  ytdSummaryStartMonth: 1
  isProbableLateFeeEnabled: true
  isSchumerBoxEnabled: true
  schumerMonthsToRepay: 36
  isInterestBreakupEnabled: true
  yearlyCycle: CYCUK00700129
  billingCycleChangeConfig:
    coolOffDaysBetweenBillingCycleChange: 0
    rules:
      - maxLimit: 10
        period: YEARLY
  templateCode: us-credit
