kind: RubyStatementPolicy
apiVersion: rrsd.zetaapps.in/v1alpha1
metadata:
  name: lsg.ruby.rubystatementpolicy.module.8001
  labels:
    rrsd.zetaapps.in/day: day-zero
  annotations:
    zeta.tech/resource-tags: '{"gitDbRepo":"tenant_configuration.aws-default-pp-mumbai.lsg","gitDbPath":"https://gitea.internal.mum1-pp.zetaapps.in/zetaengg/tenant_configuration.aws-default-pp-mumbai.lsg.git","filePath":"module_configurations/module_ruby/statement-policies/ruby-statement-policy_8001.yaml","tenantCode":"lsg"}'
  namespace: ruby
spec:
  metadata:
    id: ruby.rubystatementpolicy.module.8001
    name: ruby.rubystatementpolicy.module.8001
    description: ruby.rubystatementpolicy.module.8001
    tenantId: '600309'
    tenantCode: lsg
  validFrom: '2000-01-01T00:00:00.000+01:00'
  validTill: '2099-01-01T00:00:00.000+01:00'
  name: Statement Policy
  description: Statement Policy
  code: STMUS008001
  physicalStatementThreshold: '0'
  graceDays: 0
  payByHolidayTreatment: retainHoliday
  dueDaysCalculationMethod: DueDays
  dueDays: 2
  allowedStatementCycles:
    - billingCycle: CYCUS00800101
    - billingCycle: CYCUS00800102
    - billingCycle: CYCUS00800103
    - billingCycle: CYCUS00800104
    - billingCycle: CYCUS00800105
    - billingCycle: CYCUS00800106
    - billingCycle: CYCUS00800107
  password: function password(context) { return 'password' }
  statementTemplateCode: https://hercules-assets.mum1-pp.zetaapps.in/statement-templates/3.15.0/vera/template.html
  applyLateFeesOn: GRACE_DATE
  valueDateOfLateFees: DUE_DATE
  ytdSummaryEnabled: true
  ytdSummaryStartDate: 1
  ytdSummaryStartMonth: 1
  isProbableLateFeeEnabled: true
  isSchumerBoxEnabled: true
  schumerMonthsToRepay: 36
  isInterestBreakupEnabled: true
  yearlyCycle: CYCUS00800108
  billingCycleChangeConfig:
    coolOffDaysBetweenBillingCycleChange: 0
    rules:
      - maxLimit: 10
        period: YEARLY
  templateCode: us-credit
