apiVersion: rrsd.zetaapps.in/v1alpha1
kind: RubyStatementPolicy
metadata:
  name: lsg.ruby.rubystatementpolicy.3002
spec:
  metadata:
    id: ruby.rubystatementpolicy.3002
    name: 3002 Ruby Statement Policies
    description: 3002 Ruby Statement Policies
    requester:
      module: ruby-module-e2e
      moduleVersion: 0.0.1
    tenantId: '600309'
    tenantCode: lsg
  validFrom: '2000-01-01T23:09:01.795+07:00'
  validTill: '2888-01-01T23:09:01.795+07:00'
  name: Statement Policy
  description: Statement Policy
  code: STMUS003002
  physicalStatementThreshold: '0'
  graceDays: 0
  payByHolidayTreatment: retainHoliday
  dueDaysCalculationMethod: DueDays
  dueDays: 1
  allowedStatementCycles:
    - billingCycle: CYCUS00300201
    - billingCycle: CYCUS00300202
    - billingCycle: CYCUS00300203
    - billingCycle: CYCUS00300204
    - billingCycle: CYCUS00300205
    - billingCycle: CYCUS00300206
    - billingCycle: CYCUS00300207
  password: function password(context) { return 'password' }
  statementTemplateCode: https://hercules-assets.mum1-pp.zetaapps.in/statement-templates/3.7.0/sparrow/digital.html,https://hercules-assets.mum1-pp.zetaapps.in/statement-templates/3.7.0/sparrow/mail.html
  applyLateFeesOn: GRACE_DATE
  valueDateOfLateFees: DUE_DATE
  ytdSummaryEnabled: true
  ytdSummaryStartDate: 1
  ytdSummaryStartMonth: 1
  isProbableLateFeeEnabled: true
  lockbox:
    lockboxNumber: '123456'
    lockboxAttributes:
      - fieldName: accountNumber
        include: Y
        order: 1
      - fieldName: minimumAmountDue
        include: Y
        order: 2
      - fieldName: totalAmountDue
        include: Y
        order: 3
      - fieldName: dueDate
        include: Y
        order: 4
      - fieldName: checkDigit
        include: Y
        order: 5
    encodingType: OCR A
  metaData:
    specialTemplateCodes:
      VB: https://hercules-assets.mum1-pp.zetaapps.in/statement-templates/3.7.0/sparrow_v2/mail.html
      VXL: https://hercules-assets.mum1-pp.zetaapps.in/statement-templates/3.7.0/sparrow_v2/mail.html
  forceStatementGenerationRules: function forceStatementGenerationRules(context) { return false; }
  skipStatementRules: function skipStatementRules(context) { var annualFeeValidation; if (context.baseFee != null && context.annualMembershipLevyDate > context.statementDate && context.annualMembershipLevyDate <= context.nextStatementDate && context.firstAnniversaryUsageDate > context.statementDate && context.firstAnniversaryUsageDate <= context.nextStatementDate) { annualFeeValidation = true; } else { annualFeeValidation = false; } if (!annualFeeValidation && context.totalClosingBalance == '0' && context.isPostingAvailable == 'false') { return true; } return false;}
  isSchumerBoxEnabled: true
  schumerMonthsToRepay: 36
  isInterestBreakupEnabled: true
  yearlyCycle: CYCUS00300208
  billingCycleChangeConfig:
    coolOffDaysBetweenBillingCycleChange: 0
    isShortCycleEnabled: true
    rules:
      - maxLimit: 1
        period: YEARLY
  templateCode: us-credit
