apiVersion: rrsd.zetaapps.in/v1alpha1
kind: RubyStatementPolicy
metadata:
  name: lsg.ruby.rubystatementpolicy.3004
spec:
  metadata:
    id: ruby.rubystatementpolicy.3004
    name: 3004 Ruby Statement Policies
    description: 3004 Ruby Statement Policies
    requester:
      module: ruby-module-e2e
      moduleVersion: 0.0.1
    tenantId: '600309'
    tenantCode: lsg
  validFrom: '2000-01-01T23:09:01.795+07:00'
  validTill: '2998-01-01T23:09:01.795+07:00'
  name: Statement Policy
  description: Statement Policy
  code: STMUS003004
  physicalStatementThreshold: '0'
  graceDays: 0
  payByHolidayTreatment: retainHoliday
  dueDaysCalculationMethod: DueDays
  dueDays: 2
  allowedStatementCycles:
    - billingCycle: CYCUS00300401
    - billingCycle: CYCUS00300402
    - billingCycle: CYCUS00300403
    - billingCycle: CYCUS00300405
    - billingCycle: CYCUS00300406
    - billingCycle: CYCUS00300407
  password: function password(context) { return 'password' }
  statementTemplateCode: https://hercules-assets.mum1-pp.zetaapps.in/statement-templates/3.7.2/sparrow/digital.html,https://hercules-assets.mum1-pp.zetaapps.in/statement-templates/3.7.2/sparrow/mail.html
  applyLateFeesOn: GRACE_DATE
  valueDateOfLateFees: DUE_DATE
  ytdSummaryEnabled: true
  ytdSummaryStartDate: 1
  ytdSummaryStartMonth: 1
  metaData:
    specialTemplateCodes:
      VB: https://hercules-assets.mum1-pp.zetaapps.in/statement-templates/3.7.2/sparrow_v2/mail.html
      VXL: https://hercules-assets.mum1-pp.zetaapps.in/statement-templates/3.7.2/sparrow_v2/mail.html
  isProbableLateFeeEnabled: true
  isSchumerBoxEnabled: true
  schumerMonthsToRepay: 36
  isInterestBreakupEnabled: true
  yearlyCycle: CYCUS00300409
  billingCycleChangeConfig:
    coolOffDaysBetweenBillingCycleChange: 0
    isShortCycleEnabled: true
    rules:
      - maxLimit: 1
        period: YEARLY
  templateCode: us-credit
