apiVersion: rrsd.zetaapps.in/v1alpha1
kind: RubyStatementPolicy
metadata:
  name: lsg.ruby.rubystatementpolicy.secured.5001
  labels:
    rrsd.zetaapps.in/day: day-zero
spec:
  metadata:
    id: ruby.rubystatementpolicy.secured.5001
    name: Secured Statement Policy 5001
    tenantCode: lsg
  validFrom: '2026-01-01T00:00:00.000-05:00'
  validTill: '2099-01-01T00:00:00.000-05:00'
  code: STMUS005001
  # US Regulation Z requires at least 21 days from statement to due date
  dueDays: 21 
  graceDays: 0
  dueDaysCalculationMethod: DueDays
  applyLateFeesOn: GRACE_DATE
  valueDateOfLateFees: DUE_DATE
  # Mandatory US Transparency Features
  ytdSummaryEnabled: true
  ytdSummaryStartDate: 1
  ytdSummaryStartMonth: 1
  isProbableLateFeeEnabled: true
  isSchumerBoxEnabled: true
  # CFPB mandated 36-month payoff projection
  schumerMonthsToRepay: 36
  isInterestBreakupEnabled: true
  # Logic to ensure higher-APR balances are paid off first (CARD Act)
  templateCode: us-credit