apiVersion: rrsd.zetaapps.in/v1alpha1
kind: RubyStatementPolicy
metadata:
  name: lsg.ruby.rubystatementpolicy.3005
spec:
  metadata:
    id: ruby.rubystatementpolicy.3005
    name: 3005 Ruby Statement Policies
    description: 3005 Ruby Statement Policies
    requester:
      module: ruby-module-e2e
      moduleVersion: 0.0.1
    tenantId: '600309'
    tenantCode: lsg
  validFrom: '2000-01-01T23:09:01.795+07:00'
  validTill: '2999-01-01T23:09:01.795+07:00'
  name: Statement Policy
  description: Statement Policy
  code: STMUS003005
  physicalStatementThreshold: '0'
  graceDays: 0
  payByHolidayTreatment: retainHoliday
  dueDaysCalculationMethod: FixedDueDate
  allowedStatementCycles:
    - billingCycle: CYCUS00300501
      dueDate: 1
    - billingCycle: CYCUS00300502
      dueDate: 2
    - billingCycle: CYCUS00300503
      dueDate: 3
    - billingCycle: CYCUS00300504
      dueDate: 4
    - billingCycle: CYCUS00300505
      dueDate: 5
    - billingCycle: CYCUS00300506
      dueDate: 6
    - billingCycle: CYCUS00300507
      dueDate: 7
  password: function password(context) { return 'password' }
  statementTemplateCode: https://hercules-assets.mum1-pp.zetaapps.in/statement-templates/3.0.27/sparrow/digital.html
  applyLateFeesOn: GRACE_DATE
  valueDateOfLateFees: DUE_DATE
  ytdSummaryEnabled: true
  ytdSummaryStartDate: 1
  ytdSummaryStartMonth: 1
  isProbableLateFeeEnabled: true
  isSchumerBoxEnabled: true
  schumerMonthsToRepay: 36
  isInterestBreakupEnabled: true
  yearlyCycle: CYCUS00300508
  billingCycleChangeConfig:
    coolOffDaysBetweenBillingCycleChange: 180
    rules:
      - maxLimit: 1
        period: YEARLY
  templateCode: us-credit
