apiVersion: rrsd.zetaapps.in/v1alpha1
kind: RubyStatementPolicy
metadata:
  name: lsg.ruby.rubystatementpolicy.6002
spec:
  metadata:
    id: ruby.rubystatementpolicy.6002
    name: 6002 Ruby Statement Policies
    description: 6002 Ruby Statement Policies
    requester:
      module: ruby-module-e2e
      moduleVersion: 0.0.1
    tenantId: '600309'
    tenantCode: lsg
  validFrom: '2000-01-01T23:09:01.795+07:00'
  validTill: '2999-01-01T23:09:01.795+07:00'
  name: Statement Policy
  description: Statement Policy
  code: STMUS006002
  physicalStatementThreshold: '0'
  graceDays: 0
  payByHolidayTreatment: retainHoliday
  dueDaysCalculationMethod: DueDays
  dueDays: 2
  allowedStatementCycles:
    - billingCycle: CYCUS00600101
    - billingCycle: CYCUS00600102
    - billingCycle: CYCUS00600103
    - billingCycle: CYCUS00600104
    - billingCycle: CYCUS00600105
    - billingCycle: CYCUS00600106
    - billingCycle: CYCUS00600107
    - billingCycle: CYCUS00600108
    - billingCycle: CYCUS00600109
    - billingCycle: CYCUS00600110
    - billingCycle: CYCUS00600111
    - billingCycle: CYCUS00600112
    - billingCycle: CYCUS00600113
    - billingCycle: CYCUS00600114
    - billingCycle: CYCUS00600115
    - billingCycle: CYCUS00600116
    - billingCycle: CYCUS00600117
    - billingCycle: CYCUS00600118
    - billingCycle: CYCUS00600119
    - billingCycle: CYCUS00600120
    - billingCycle: CYCUS00600121
    - billingCycle: CYCUS00600122
    - billingCycle: CYCUS00600123
    - billingCycle: CYCUS00600124
    - billingCycle: CYCUS00600125
    - billingCycle: CYCUS00600126
    - billingCycle: CYCUS00600127
    - billingCycle: CYCUS00600128
  password: function password(context) { return 'password' }
  statementTemplateCode: https://hercules-assets.mum1-pp.zetaapps.in/statement-templates/3.6.11/sparrow/digital.html,https://hercules-assets.mum1-pp.zetaapps.in/statement-templates/3.6.11/sparrow/mail.html
  applyLateFeesOn: GRACE_DATE
  valueDateOfLateFees: DUE_DATE
  ytdSummaryEnabled: true
  ytdSummaryStartDate: 1
  ytdSummaryStartMonth: 1
  isProbableLateFeeEnabled: true
  isSchumerBoxEnabled: true
  schumerMonthsToRepay: 36
  isInterestBreakupEnabled: true
  yearlyCycle: CYCUS00600129
  billingCycleChangeConfig:
    coolOffDaysBetweenBillingCycleChange: 0
    isShortCycleEnabled: true
    rules:
      - maxLimit: 1
        period: YEARLY
  templateCode: us-credit
