kind: Configuration
apiVersion: rrsd.zetaapps.in/v1alpha1
metadata:
  name: lsg.auraapps.configuration.module.credit-allocation-program-test2.account
  labels:
    rrsd.zetaapps.in/day: day-zero
    module: auraapps
    rrsd.zetaapps.in/space: aws-default-pp-mumbai
  annotations:
    zeta.tech/resource-tags: '{"gitDbRepo":"tenant_configuration.aws-default-pp-mumbai.lsg","gitDbPath":"https://gitea.internal.mum1-pp.zetaapps.in/zetaengg/tenant_configuration.aws-default-pp-mumbai.lsg.git","filePath":"module_configurations/module_auraapps/credit-allocation-program/account_credit-allocation-program-test2.yaml","tenantCode":"lsg"}'
  namespace: auraapps
spec:
  metadata:
    id: auraapps.configuration.module.credit-allocation-program-test2.account
    name: auraapps.configuration.module.credit-allocation-program-test2.account
    description: auraapps.configuration.module.credit-allocation-program-test2.account
    tenantId: '600309'
    tenantCode: lsg
  config:
    format: YAML
    schemaUrl: http://localhost
    schemaInlineContent: |
      {"properties":{"accountHolderType":{"type":"string"},"accountProductCode":{"type":"string"},"attributes":{"type":"object"},"legalAccountHolderID":{"type":"string"},"requestID":{"type":"string"},"templateCode":{"type":"object"}},"type":"object"}
    key: key
    isEncrypted: false
    useVault: false
    value:
      accountStatus: []
      directed: true
      code: CRAUS00609
      version: 1
      description: Unmatched and Matched Refunds
      lienMarkedDebitPosting: false
      name: Credit Allocation Principal Debits
      precedenceCode: '10'
      status: ENABLED
      validFrom: '2000-01-01T00:00:00.000-05:00'
      validUntil: '2999-01-01T00:00:00.000-05:00'
      voucherCodes:
      - CARD_CASH_CLEARANCE_REFUND
      - CARD_CREDIT_ADJUSTMENTS
      - CARD_PURCHASE_CLEARANCE_REFUND
      - CARD_CASH_CREDIT_ADJUSTMENTS
      - CARD_PURCHASE_CREDIT_ADJUSTMENTS
    metadata: null
    id: auraapps.creditallocationprogram.module.credit-allocation-program-test
    name: auraapps.creditallocationprogram.module.credit-allocation-program-test
    description: auraapps.creditallocationprogram.module.credit-allocation-program-test
    tenantId: '600309'
    tenantCode: lsg
