apiVersion: rrsd.zetaapps.in/v1alpha1
kind: StatementPolicy
metadata:
  name: verapp.statement.statementpolicy.8001
spec:
  metadata:
    id: statement.statementpolicy.8001
    name: 8001 Statement Generation Policies
    description: 8001 Statement Generation Policies
    requester:
      module: statement
      moduleVersion: 0.0.1
    tenantId: '600309'
    tenantCode: verapp
  validFrom: '2010-01-01T00:00:00.000-07:00'
  validTill: '2999-12-31T00:00:00.000-07:00'
  name: Statement Generation Policy
  description: Statement Generation Policy
  code: STMGENUS008001
  templateCode: us-credit
  messageConfigs:
    maxMessageCount: 2
    ruleList:
      - name: STATEMENT_PDF_MESSAGE
        code: STMT_RULE_1
        status: ENABLED
        priority: 1
        order: 1
        condition: input.accountHolder.address!= null && input.accountHolder.address.state=='NY'
        content: New York residents may contact the New York State Department of Financial Services by telephone at 1-800-342-3736 or visit <a href="https://www.dfs.ny.gov" target="_blank" rel="noopener noreferrer">Home</a> for free information on comparative credit card rates, fees and grace periods.
        frequency: EVERYTIME
        metaData:
          isSuppressed: false
      - name: STATEMENT_PDF_MESSAGE
        code: STMT_RULE_2
        status: ENABLED
        priority: 2
        order: 1
        condition: input.accountHolder.tags != null && input.accountHolder.tags.get('DECEASE') != null && input.accountHolder.tags.get('DECEASE').value=='Y'
        content: This account has been designated as belonging to a deceased individual. Please accept our condolences. Please contact us at 1-800-769-1306 for assistance.
        frequency: EVERYTIME
        metaData:
          isSuppressed: false
      - name: STATEMENT_PDF_MESSAGE
        code: STMT_RULE_3
        status: ENABLED
        priority: 3
        order: 1
        condition: input.rubyAccountStatusDetails.get('SCRAStatus') != null && input.rubyAccountStatusDetails.get('SCRAStatus').value=='LEVEL_1'
        content: This account has been designated for benefits under the Servicemembers Civil Relief Act. Thank you for your service to our country.
        frequency: EVERYTIME
        metaData:
          isSuppressed: false
      - name: STATEMENT_PDF_MESSAGE
        code: STMT_RULE_4
        status: ENABLED
        priority: 4
        order: 1
        condition: input.rubyAccountStatusDetails.get('accountClosureStatus') != null && input.rubyAccountStatusDetails.get('accountClosureStatus').value=='LEVEL_2'
        content: Your account is now closed  and no purchases are allowed. Please continue to make payments until the balance is paid in full
        frequency: EVERYTIME
        metaData:
          isSuppressed: false
      - name: STATEMENT_PDF_MESSAGE
        code: STMT_RULE_5
        status: ENABLED
        priority: 5
        order: 1
        condition: input.billingSummary.disputeDataDto != null && input.billingSummary.disputeDataDto.totalOutstandingDisputedClosingBalance>0
        content: We are currently investigating your dispute. In the interim, you are not responsible for the disputed charges.
        frequency: EVERYTIME
        metaData:
          isSuppressed: false
      - name: STATEMENT_PDF_MESSAGE
        code: STMT_RULE_6
        status: ENABLED
        priority: 6
        order: 1
        condition: input.rubyAccountStatusDetails.get('manualBundleStatus') != null && input.rubyAccountStatusDetails.get('manualBundleStatus').value=='MBS1' && input.rubyAccountStatusDetails.get('balanceStatus') != null && (input.rubyAccountStatusDetails.get('balanceStatus').value=='LEVEL_0' || input.rubyAccountStatusDetails.get('balanceStatus').value=='LEVEL_1')
        content: We are currenly investigating your fraud claim and will contact you once the investigation is complete.
        frequency: EVERYTIME
        metaData:
          isSuppressed: false
      - name: STATEMENT_PDF_MESSAGE
        code: STMT_RULE_7
        status: ENABLED
        priority: 7
        order: 1
        condition: (input.rubyAccountStatusDetails.get('autoChargeOffStatus') != null && (input.rubyAccountStatusDetails.get('autoChargeOffStatus').value=='LEVEL_1' || input.rubyAccountStatusDetails.get('autoChargeOffStatus').value=='LEVEL_2')) || (input.rubyAccountStatusDetails.get('manualChargeOffStatus') != null && (input.rubyAccountStatusDetails.get('manualChargeOffStatus').value=='LEVEL_1' || input.rubyAccountStatusDetails.get('manualChargeOffStatus').value=='LEVEL_2'))
        content: Your account has been charged off due to delinquency. This does not change your obligation to pay.
        frequency: EVERYTIME
        metaData:
          isSuppressed: false
      - name: STATEMENT_PDF_MESSAGE
        code: STMT_RULE_8
        status: ENABLED
        priority: 8
        order: 1
        condition: input.rubyAccountStatusDetails.get('delinquencyStatus') != null && input.rubyAccountStatusDetails.get('delinquencyStatus').value == 'LEVEL_2'
        content: Your account is now past due. Please make a payment or contact us at 1-800-769-1306 to discuss your repayment options.
        frequency: EVERYTIME
        metaData:
          isSuppressed: false
      - name: STATEMENT_PDF_MESSAGE
        code: STMT_RULE_9
        status: ENABLED
        priority: 9
        order: 1
        condition: input.rubyAccountStatusDetails.get('delinquencyStatus') != null && (input.rubyAccountStatusDetails.get('delinquencyStatus').value == 'LEVEL_3' || input.rubyAccountStatusDetails.get('delinquencyStatus').value == 'LEVEL_4')
        content: Your account is seriously past due. We are here to help and invite you to contact us for a review of your repayment optons at 1-800-769-1306.
        frequency: EVERYTIME
        metaData:
          isSuppressed: false
      - name: STATEMENT_PDF_MESSAGE
        code: STMT_RULE_10
        status: ENABLED
        priority: 10
        order: 1
        condition: input.rubyAccountStatusDetails.get('delinquencyStatus') != null && (input.rubyAccountStatusDetails.get('delinquencyStatus').value == 'LEVEL_5' || input.rubyAccountStatusDetails.get('delinquencyStatus').value == 'LEVEL_6' || input.rubyAccountStatusDetails.get('delinquencyStatus').value == 'LEVEL_7' || input.rubyAccountStatusDetails.get('delinquencyStatus').value == 'LEVEL_8' || input.rubyAccountStatusDetails.get('delinquencyStatus').value == 'LEVEL_9')
        content: Your account is extremely past due and may charge off if payment is not made soon. We would like to help and invite you to contact us to discuss options at 1-800-769-1306.
        frequency: EVERYTIME
        metaData:
          isSuppressed: false
      - name: STATEMENT_PDF_MESSAGE
        code: STMT_RULE_11
        status: ENABLED
        priority: 11
        order: 1
        condition: input.rubyAccountStatusDetails.get('balanceStatus') != null && (input.rubyAccountStatusDetails.get('balanceStatus').name == 'APPROVED_OVERLIMIT' || input.rubyAccountStatusDetails.get('balanceStatus').name == 'CRITICALLY_OVERLIMIT')
        content: Exceeding your credit limit will result in additional charges, as outlined in your credit agreement. To bring your account back within its limit, please make the minimum payment indicated. You may not be able to use your card until your balance is within the agreed limit.
        frequency: EVERYTIME
        metaData:
          isSuppressed: false
          messageHeader: You have exceeded your credit limit
  rewardConfig:
    showSummary: true
    showIssuance: true
    showStatement: false
