kind: ProductBundle
apiVersion: rrsd.zetaapps.in/v1alpha1
metadata:
  name: lsg.aether.productbundle.bankxee-secured-card
  labels:
    rrsd.zetaapps.in/day: day-one
  namespace: aether

spec:
  metadata:
    id: aether.productbundle.bankxee-secured-card
    name: Bank Xee Secured Card Bundle

    description: Secured Card for FICO below 580 or high risk_pulse_score customers

    requester:
      module: aether
      moduleVersion: 0.0.1
    tenantId: '600309'
    tenantCode: lsg

  code: PBXEE-SECURED-CARD-001

  blueprintCode: PBBXEESC0001
  blueprintName: Bank Xee US Secured Card Blueprint

  bannerImageUrl: https://hercules-assets.mum1-pp.zetaapps.in/common-assets/3.0.316/business-components/blueprints-list/images/banners/consumer_durable_credit.png
  bundleProviderCode: BPRINZZ0001

  name: Bank Xee Secured Card

  description: Tier 2 Deep Subprime - FICO below 580 or high risk_pulse_score

  picture: https://hercules-assets.mum1-pp.zetaapps.in/common-assets/3.0.328/business-components/blueprints-list/images/cards/us-credit.jpg

  productBundlePolicies:

  
    receiverPolicy:
      
      onboardReceiver: false



    identityPolicy:
      # WHY:  Phone mandatory for US OTP
      isPhoneMandatory: true
      # WHY:  Email mandatory for statements
      isEmailMandatory: true
      defaultEmailLabel: 'primary'
      defaultPhoneLabel: 'primary'

    activationPolicy:
      # WHY:  Auto activate once all artefacts issued
      activateAccount: true

  componentProducts:
    - alias: PORUS-RESOURCE
      product:
        externalProductCode: RPXEE00SC001
      dependentCompositeTypes:
        - PAYMENT_PRODUCT
    - alias: PRIMARY_CARD_VIRTUAL
      product:
        externalProductCode: FFXEE00SC001
      dependentCompositeTypes:
        - PAYMENT_PRODUCT
    - alias: RUBY_PAP-PAYMENT_ACCOUNT
      product:
        externalProductCode: PAPZZXEE00SC001
      dependentCompositeTypes:
        - PAYMENT_PRODUCT
    - alias: RUBY-TXN_ACCOUNT
      product:
        externalProductCode: RAPXEE00SC001
      dependentCompositeTypes:
        - TRANSACTION_ACCOUNT_PRODUCT